### ISSUE TITLE
READ.ME might be incorrect

### ISSUE THREAD

**Issue by bittebak** [akserg/angular.dart.ui.demo#4]
I'm trying to run the demo, but no luck so far.

0. get angular.dart.ui
Running pub get does not fetch angular.dart.ui from the pubserver
I cloned it:
git clone https://github.com/akserg/angular.dart.ui.git

1.Git branche
The read.me states "git checkout -b gh_pages"

but the branche is called gh-pages.

2. pub get missing?
When running without a pub get, various packages are missing

3. la?
- set `DART_SDK` environment variable `export DART_SDK=/path/to/dart-sdk`la 
Is the 'la intended?

4. working dir for generate.dart
- change  directory to `angular.dart.ui.demo/bin'
- run `dart bin/generator.dart`

If you run bin/generator.dart from angular.dart.ui.demo/bin, generator.dart cannot be found.
Running 'dart bin/generate.dart'  from angular.dart.ui.demo gives the best results..

5. Error
However it produces an error.

dart bin/generator.dart 
pathToSdk: /App_extra/dart/dart 2/dart-sdk
entryPoint: web/index.dart
classAnnotations: angular.core.NgComponent, angular.core.NgController, angular.core.NgDirective, angular.core.NgFilter, injectable.InjectableService, angular.core.service.NgInjectableService, angular.ui.utils.injectable_service, di.annotations.Injectable
output: web/di_factories_gen.dart
packageRoots: [packages]
Unhandled exception:
Unable to resolve type for constructor parameter "_formatter" for type "TypeaheadConverter" in /Users/marcprive/workspaces/dart/angular.dart.ui/lib/typeahead/typeahead_decorator.dart
#0      process_classes.<anonymous closure>.<anonymous closure> (package:di/generator.dart:178:11)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:397)
#2      ListIterable.join (dart:_internal/iterable.dart:148)
#3      process_classes.<anonymous closure> (package:di/generator.dart:200:14)
#4      List.forEach (dart:core-patch/growable_array.dart:228)
#5      process_classes (package:di/generator.dart:150:18)
#6      printLibraryCode.<anonymous closure> (package:di/generator.dart:115:20)
#7      _HashMap&&_LinkedHashMapMixin.forEach (dart:collection-patch/collection_patch.dart:967)
#8      printLibraryCode (package:di/generator.dart:82:27)
#9      generateCode (package:di/generator.dart:70:26)
#10     main (package:di/generator.dart:46:26)
#11     _runDiGenerator (file:///Users/marcprive/workspaces/dart/angular.dart.ui.demo/bin/generator.dart:37:20)
#12     main (file:///Users/marcprive/workspaces/dart/angular.dart.ui.demo/bin/generator.dart:23:18)

**Comment by akserg** [comment]
Out of date. Project heavily updating.
